sudo: false

language: node_js

install:
  - npm install
  - npm install libxmljs || true

node_js:
  - "10"
  - "12"
  - "14"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  edge: true
  api_key: "$NPM_TOKEN"
  cleanup: true  # avoids adding libxmljs to dependencies
  on:
    tags: true
    node: "node"
